version: '3.8'

networks:
  app_net:
    driver: bridge

services:
  # Backend 1
  backend-1:
    image: admin-back
    container_name: backend-1
    ports:
      - "8081:8080"
    networks:
      - app_net

  # Backend 2
  backend-2:
    image: admin-back
    container_name: backend-2
    ports:
      - "8082:8080"
    networks:
      - app_net

  # Node Exporter 1
  node-exporter-1:
    image: prom/node-exporter
    container_name: node-exporter-1
    ports:
      - "9101:9100"
    networks:
      - app_net

  # Node Exporter 2
  node-exporter-2:
    image: prom/node-exporter
    container_name: node-exporter-2
    ports:
      - "9102:9100"
    networks:
      - app_net

  # Prometheus
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app_net

  # Grafana
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - app_net

  # Zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - app_net

  # Kafka
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - app_net
