global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'backend-1'
    static_configs:
      - targets: ['backend-1:8080']

  - job_name: 'backend-2'
    static_configs:
      - targets: ['backend-2:8080']

  - job_name: 'node-exporter-1'
    static_configs:
      - targets: ['node-exporter-1:9100']

  - job_name: 'node-exporter-2'
    static_configs:
      - targets: ['node-exporter-2:9100']
